ENVIRON:
  GOOGLE_APPLICATION_CREDENTIALS: "/etc/credentials.json"

DATASET:
  ORIGINAL:
    DIR_PATH: "/detectron2_repo/split_damages/datasets/coco/"
    IMAGES_PATH: "/images/"
    TRAIN_PATH: "/annotations/instances_train.json"
    TEST_PATH: "/annotations/instances_test.json"
    VAL_PATH: "/annotations/instances_validation.json"
  AUGMENTED:
    DIR_PATH: "/detectron2_repo/"
    IMAGES_PATH: "/images/"
    TRAIN_PATH: "/train_total_aug.json"
    TEST_PATH: "/test_total.json"
    VAL_PATH: "/validation_total.json"
  LOCAL:
    DIR_PATH: "/share/"
    IMAGES_PATH: "/images/"
    TRAIN_PATH: "/dent_ding_train_30.json"
    TEST_PATH: "/dent_ding_test_30.json"
    VAL_PATH: "/dent_ding_valid_30.json"

MODEL:
  OUT_PATH: "output/"
  CONFIG: "COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml"

GOOGLE_STORAGE:
  ORIGINAL:
    BUCKET: "gs://hptuning2/"
    DATAFILE: "split_damages.zip"
  AUGMENTED:
    BUCKET: "gs://hptuning2/"
    DATAFILE: "dent_aug.zip"

JSONS:
  DICE_DICT: 'dice_dict.json'
  TRAIN_LOSS: 'trainloss.json'
